//! A2.9 chat-template parity: byte-identical rendering against the
//! Jinja2-derived goldens in `tests/fixtures/golden-templates.json`
//! (generated by `tests/fixtures/gen_template_fixtures.py`; oracle notes in
//! `tests/fixtures/templates.json`).
//!
//! Covers every reference template (llama3, qwen25, mistral) over the full
//! context matrix, including failure parity (the mistral `tool_roundtrip`
//! case raises in both engines) and render-twice repeatability.

use r9v_loader::{render_template_vars, ChatContext, ChatMessage, LoaderError, ToolCall};
use serde_json::Value;
use std::collections::BTreeMap;
use std::panic::catch_unwind;

mod common;
use common::ordered_json::{self, OrderedValue};

fn fixture_dir() -> String {
    format!("{}/tests/fixtures", env!("CARGO_MANIFEST_DIR"))
}

fn str_field(v: &OrderedValue, key: &str) -> String {
    v.get(key).and_then(|f| f.as_str()).unwrap_or("").to_owned()
}

fn message(v: &OrderedValue) -> ChatMessage {
    let mut m = ChatMessage {
        role: str_field(v, "role"),
        content: str_field(v, "content"),
        tool_calls: Vec::new(),
        reasoning_content: None,
    };
    if let Some(calls) = v.get("tool_calls").and_then(|c| c.as_array()) {
        for call in calls {
            let function = call.get("function");
            m.tool_calls.push(ToolCall {
                name: function.map(|f| str_field(f, "name")).unwrap_or_default(),
                arguments: function
                    .map(|f| str_field(f, "arguments"))
                    .unwrap_or_default(),
                id: call.get("id").and_then(|i| i.as_str()).map(str::to_owned),
            });
        }
    }
    m
}

fn render_case(tmpl: &str, ctx_name: &str, contexts: &OrderedValue) -> Result<String, String> {
    let dir = fixture_dir();
    let source = std::fs::read_to_string(format!("{dir}/template-{tmpl}.jinja")).unwrap();
    let ctx = contexts.get(ctx_name).expect("context must exist");
    let mut chat = ChatContext {
        messages: ctx
            .get("messages")
            .and_then(|m| m.as_array())
            .unwrap()
            .iter()
            .map(message)
            .collect(),
        add_generation_prompt: ctx
            .get("add_generation_prompt")
            .and_then(|f| f.as_bool())
            .unwrap(),
        bos_token: ctx
            .get("bos_token")
            .and_then(|f| f.as_str())
            .map(str::to_owned),
        eos_token: ctx
            .get("eos_token")
            .and_then(|f| f.as_str())
            .map(str::to_owned),
        enable_thinking: None,
        tools: None,
        tool_choice: None,
        extra: Default::default(),
    };
    if let Some(tools) = ctx.get("tools") {
        chat.tools = Some(ordered_json::to_template_value(tools));
    }
    r9v_loader::render_chat_template(&source, &chat).map_err(|e| e.to_string())
}

fn golden_cases() -> (Value, OrderedValue) {
    let dir = fixture_dir();
    let golden: Value = serde_json::from_str(
        &std::fs::read_to_string(format!("{dir}/golden-templates.json")).unwrap(),
    )
    .unwrap();
    // Contexts parse order-preservingly: `.items()` iteration order is part
    // of the oracle contract.
    let contexts =
        OrderedValue::parse(&std::fs::read_to_string(format!("{dir}/contexts.json")).unwrap())
            .unwrap();
    (golden, contexts)
}

/// Every golden case renders byte-identically (or fails, exactly when the
/// oracle fails).
#[test]
fn golden_parity() {
    let (golden, contexts) = golden_cases();
    let cases = golden["cases"].as_array().unwrap();
    assert_eq!(
        cases.len(),
        15,
        "golden matrix must cover 3 templates x 5 contexts"
    );
    for case in cases {
        let tmpl = case["template"].as_str().unwrap();
        let ctx_name = case["context"].as_str().unwrap();
        let label = format!("{tmpl}/{ctx_name}");
        match render_case(tmpl, ctx_name, &contexts) {
            Ok(got) => {
                assert_eq!(
                    case["status"].as_str().unwrap(),
                    "ok",
                    "{label}: oracle failed but we rendered"
                );
                assert_eq!(
                    got,
                    case["output"].as_str().unwrap(),
                    "{label}: byte mismatch"
                );
            }
            Err(err) => {
                assert_eq!(
                    case["status"].as_str().unwrap(),
                    "error",
                    "{label}: oracle rendered but we failed: {err}"
                );
            }
        }
    }
}

/// Rendering is deterministic: two passes over every ok case agree byte-wise.
#[test]
fn repeatability() {
    let (golden, contexts) = golden_cases();
    for case in golden["cases"].as_array().unwrap() {
        if case["status"].as_str().unwrap() != "ok" {
            continue;
        }
        let tmpl = case["template"].as_str().unwrap();
        let ctx_name = case["context"].as_str().unwrap();
        let first = render_case(tmpl, ctx_name, &contexts).unwrap();
        let second = render_case(tmpl, ctx_name, &contexts).unwrap();
        assert_eq!(first, second, "{tmpl}/{ctx_name}: render not repeatable");
    }
}

fn render_str(source: &str) -> Result<String, LoaderError> {
    render_template_vars(source, BTreeMap::new())
}

#[test]
fn namespace_counter_and_last_across_iterations() {
    let res = catch_unwind(|| {
        let tmpl = r#"{% set ns = namespace(count=0, last="") -%}
{% for item in ["apple", "banana", "cherry"] -%}
  {% set ns.count = ns.count + 1 -%}
  {% set ns.last = item -%}
{% endfor -%}
count={{ ns.count }}, last={{ ns.last }}"#;
        let out = render_str(tmpl).expect("render should succeed");
        assert_eq!(out, "count=3, last=cherry");
    });
    assert!(res.is_ok(), "namespace counter test panicked");
}

#[test]
fn namespace_nested_loops_and_scopes() {
    let res = catch_unwind(|| {
        let tmpl = r#"{% set outer_var = "outer" -%}
{% set ns = namespace(total=0, last_inner="", runs=0) -%}
{% for i in [1, 2, 3] -%}
  {% set loop_var = i -%}
  {% for j in [10, 20] -%}
    {% set inner_var = j -%}
    {% set ns.total = ns.total + i * j -%}
    {% set ns.last_inner = j -%}
    {% set ns.runs = ns.runs + 1 -%}
  {% endfor -%}
  {% set outer_var = "shadowed_in_loop" -%}
{% endfor -%}
total={{ ns.total }}, last_inner={{ ns.last_inner }}, runs={{ ns.runs }}, outer={{ outer_var }}"#;
        let out = render_str(tmpl).expect("nested render should succeed");
        // 1*10 + 1*20 + 2*10 + 2*20 + 3*10 + 3*20 = 30 + 60 + 90 = 180
        assert_eq!(out, "total=180, last_inner=20, runs=6, outer=outer");

        // Explicit inner shadowing preserves outer namespace after scope exit
        let tmpl_shadow = r#"{% set ns = namespace(val="outer") -%}
{% for x in [1] -%}
  {% set ns = namespace(val="inner") -%}
  {% set ns.val = "inner_mutated" -%}
  inner={{ ns.val }}
{% endfor -%}
outer={{ ns.val }}"#;
        let out_shadow = render_str(tmpl_shadow).expect("shadow render should succeed");
        assert_eq!(out_shadow, "inner=inner_mutated\nouter=outer");

        // Macro scope mutation of declaring namespace
        let tmpl_macro = r#"{% set ns = namespace(val=10) -%}
{% macro add_five() -%}
  {% set ns.val = ns.val + 5 -%}
{% endmacro -%}
{{ add_five() -}}
val={{ ns.val }}"#;
        let out_macro = render_str(tmpl_macro).expect("macro render should succeed");
        assert_eq!(out_macro, "val=15");

        // Macro called inside loop mutating outer namespace
        let tmpl_macro_loop = r#"{% set ns = namespace(count=0) -%}
{% macro inc() -%}
  {% set ns.count = ns.count + 1 -%}
{% endmacro -%}
{% for x in [1, 2, 3] -%}
  {{ inc() -}}
{% endfor -%}
count={{ ns.count }}"#;
        let out_macro_loop = render_str(tmpl_macro_loop).expect("macro in loop should succeed");
        assert_eq!(out_macro_loop, "count=3");

        // Tuple unpack assignment on namespace attributes
        let tmpl_tuple = r#"{% set ns = namespace(x=0, y=0) -%}
{% set ns.x, ns.y = 10, 20 -%}
x={{ ns.x }}, y={{ ns.y }}"#;
        let out_tuple = render_str(tmpl_tuple).expect("tuple unpack should succeed");
        assert_eq!(out_tuple, "x=10, y=20");

        // Loop over pairs mutating namespace attributes
        let tmpl_pairs = r#"{% set ns = namespace(sum_x=0, sum_y=0) -%}
{% for a, b in [[1, 10], [2, 20], [3, 30]] -%}
  {% set ns.sum_x = ns.sum_x + a -%}
  {% set ns.sum_y = ns.sum_y + b -%}
{% endfor -%}
sum_x={{ ns.sum_x }}, sum_y={{ ns.sum_y }}"#;
        let out_pairs = render_str(tmpl_pairs).expect("pairs loop should succeed");
        assert_eq!(out_pairs, "sum_x=6, sum_y=60");
    });
    assert!(res.is_ok(), "nested loops and scopes test panicked");
}

#[test]
fn namespace_missing_attr_and_errors() {
    let res = catch_unwind(|| {
        let tmpl = r#"{% set ns = namespace() -%}
defined={{ ns.missing is defined }}, undefined={{ ns.missing is undefined }}, truthy={{ not not ns.missing }}, default={{ ns.missing | default("fallback", true) }}
{% set ns.new_attr = 42 -%}
new={{ ns.new_attr }}"#;
        let out = render_str(tmpl).expect("missing attr render should succeed");
        assert_eq!(
            out,
            "defined=False, undefined=True, truthy=False, default=fallback\nnew=42"
        );

        // Setting attribute on non-namespace fails with typed TemplateRender error
        let tmpl_err1 = "{% set x = 42 %}{% set x.attr = 1 %}";
        match render_str(tmpl_err1) {
            Err(LoaderError::TemplateRender { detail }) => {
                assert!(detail.contains("cannot set attribute on non-namespace 'x'"));
            }
            other => panic!("expected TemplateRender error, got {other:?}"),
        }

        // Setting attribute on undeclared identifier fails with typed error
        let tmpl_err2 = "{% set undeclared.attr = 1 %}";
        match render_str(tmpl_err2) {
            Err(LoaderError::TemplateRender { detail }) => {
                assert!(detail.contains("cannot set attribute on non-namespace 'undeclared'"));
            }
            other => panic!("expected TemplateRender error, got {other:?}"),
        }
    });
    assert!(res.is_ok(), "missing attr test panicked");
}

#[test]
fn namespace_resource_budgets() {
    let res = catch_unwind(|| {
        // Range loop iteration budget trips
        let tmpl_loop = r#"{% set ns = namespace(count=0) -%}
{% for i in range(200000) -%}
  {% set ns.count = ns.count + 1 -%}
{% endfor -%}"#;
        match render_str(tmpl_loop) {
            Err(LoaderError::Limit { what, .. }) => {
                assert!(what.contains("range") || what.contains("loop") || what.contains("steps"));
            }
            other => panic!("expected Limit error for huge range, got {other:?}"),
        }

        // Huge string repetition budget trips on namespace assignment
        let tmpl_str = r#"{% set ns = namespace(s="a") -%}
{% set ns.s = "a" * 1000000000 -%}"#;
        match render_str(tmpl_str) {
            Err(LoaderError::Limit { what, .. }) => {
                assert!(what.contains("repeat") || what.contains("bytes"));
            }
            other => panic!("expected Limit error for huge string repeat, got {other:?}"),
        }
    });
    assert!(res.is_ok(), "resource budgets test panicked");
}
