// SPDX-License-Identifier: Apache-2.0
//! Deterministic HIP and Rust struct emission from canonical ABI descriptions (Spec 4 §7).

use std::fmt::Write;

use crate::abi::types::{AbiStruct, AbiType, KERNEL_PTR_ALIGNMENT_BYTES};

/// Emits the HIP C++ argument struct definition for an ABI struct (Spec 4 §7).
pub fn emit_hip_struct(abi: &AbiStruct) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "// ABI argument struct for op '{}' (Spec 4 §7).",
        abi.op.as_str()
    );
    let _ = writeln!(out, "// Generated by r9v-kgen. DO NOT HAND-EDIT.");
    let _ = writeln!(out, "struct {} {{", abi.name);

    for field in &abi.fields {
        let _ = writeln!(
            out,
            "    // Offset: {} B, Size: {} B. {}",
            field.offset,
            field.size(),
            field.doc
        );
        match &field.ty {
            AbiType::Pointer {
                pointee,
                is_const,
                is_restrict,
                ..
            } => {
                let const_str = if *is_const { "const " } else { "" };
                let restrict_str = if *is_restrict { " __restrict__" } else { "" };
                let _ = writeln!(
                    out,
                    "    {}{}*{} {};",
                    const_str,
                    pointee.hip_type_name(),
                    restrict_str,
                    field.name
                );
            }
            AbiType::Scalar(s) => {
                let _ = writeln!(out, "    {} {};", s.hip_type_name(), field.name);
            }
        }
    }

    let _ = writeln!(out, "}};");
    out
}

/// Emits HIP C++ unpacking statements applying `__builtin_assume_aligned` (Spec 4 §7).
///
/// For every pointer field, asserts 256-byte alignment to enable vectorized compiler lowering.
/// Nullable pointers are guarded with a nullptr ternary before applying `__builtin_assume_aligned`.
pub fn emit_hip_assume_aligned(abi: &AbiStruct, var_name: &str) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "    // Assume 256-byte alignment on device pointers (Spec 4 §7)."
    );
    for field in &abi.fields {
        if let AbiType::Pointer {
            pointee,
            is_const,
            is_nullable,
            ..
        } = &field.ty
        {
            let const_str = if *is_const { "const " } else { "" };
            if *is_nullable {
                let _ = writeln!(
                    out,
                    "    {}{}* {} = {}.{} ? ({}{}*)__builtin_assume_aligned({}.{}, {}) : nullptr;",
                    const_str,
                    pointee.hip_type_name(),
                    field.name,
                    var_name,
                    field.name,
                    const_str,
                    pointee.hip_type_name(),
                    var_name,
                    field.name,
                    KERNEL_PTR_ALIGNMENT_BYTES
                );
            } else {
                let _ = writeln!(
                    out,
                    "    {}{}* {} = ({}{}*)__builtin_assume_aligned({}.{}, {});",
                    const_str,
                    pointee.hip_type_name(),
                    field.name,
                    const_str,
                    pointee.hip_type_name(),
                    var_name,
                    field.name,
                    KERNEL_PTR_ALIGNMENT_BYTES
                );
            }
        }
    }
    out
}

/// Emits the Rust `#[repr(C)]` argument struct definition for an ABI struct (Spec 4 §7).
pub fn emit_rust_struct(abi: &AbiStruct) -> String {
    let mut out = String::new();

    let _ = writeln!(
        out,
        "/// ABI argument struct for op `{}` (Spec 4 §7).",
        abi.op.as_str()
    );
    let _ = writeln!(out, "///");
    let _ = writeln!(
        out,
        "/// Total size: {} bytes, alignment: {} bytes.",
        abi.size, abi.alignment
    );
    let _ = writeln!(out, "/// Generated by r9v-kgen. DO NOT HAND-EDIT.");
    let _ = writeln!(out, "#[repr(C)]");
    let _ = writeln!(out, "#[derive(Debug, Clone, Copy, PartialEq)]");
    let _ = writeln!(out, "#[allow(non_camel_case_types)]");
    let _ = writeln!(out, "pub struct {} {{", abi.name);

    for field in &abi.fields {
        let _ = writeln!(out, "    /// Offset: {} B. {}", field.offset, field.doc);
        match &field.ty {
            AbiType::Pointer {
                pointee, is_const, ..
            } => {
                let ptr_kw = if *is_const { "*const" } else { "*mut" };
                let _ = writeln!(
                    out,
                    "    pub {}: {} {},",
                    field.name,
                    ptr_kw,
                    pointee.rust_type_name()
                );
            }
            AbiType::Scalar(s) => {
                let _ = writeln!(out, "    pub {}: {},", field.name, s.rust_type_name());
            }
        }
    }

    let _ = writeln!(out, "}}");
    out
}

/// Sorts input variants deterministically by name and detects inconsistent duplicate collisions (Spec 4 §7).
fn sort_and_dedup_variants(
    structs: &[AbiStruct],
) -> Result<Vec<&AbiStruct>, crate::error::KgenError> {
    let mut sorted: Vec<&AbiStruct> = structs.iter().collect();
    sorted.sort_by(|a, b| a.name.cmp(&b.name));

    let mut result: Vec<&AbiStruct> = Vec::with_capacity(sorted.len());
    for s in sorted {
        if let Some(last) = result.last() {
            if last.name == s.name {
                if *last != s {
                    return Err(crate::error::KgenError::InconsistentVariantCollision {
                        name: s.name.clone(),
                        details: format!(
                            "conflicting definitions for variant '{}' (size {} vs {}, fields {} vs {})",
                            s.name, last.size, s.size, last.fields.len(), s.fields.len()
                        ),
                    });
                }
                // Identical duplicate, skip
                continue;
            }
        }
        result.push(s);
    }
    Ok(result)
}

/// Emits the complete standalone C++ / HIP header file for all provided ABI structs (Spec 4 §7).
pub fn emit_all_hip_header(structs: &[AbiStruct]) -> Result<String, crate::error::KgenError> {
    let ordered = sort_and_dedup_variants(structs)?;
    let mut out = String::new();
    let _ = writeln!(out, "// SPDX-License-Identifier: Apache-2.0");
    let _ = writeln!(
        out,
        "// Auto-generated by r9v-kgen ABI generator (Spec 4 §7)."
    );
    let _ = writeln!(
        out,
        "// Pinned alignment: {} bytes. DO NOT HAND-EDIT.",
        KERNEL_PTR_ALIGNMENT_BYTES
    );
    let _ = writeln!(out, "#pragma once");
    let _ = writeln!(out);
    let _ = writeln!(out, "#include <stddef.h>");
    let _ = writeln!(out, "#include <stdint.h>");
    let _ = writeln!(out);
    let _ = writeln!(out, "#ifdef __HIP__");
    let _ = writeln!(out, "#include <hip/hip_runtime.h>");
    let _ = writeln!(out, "#include <hip/hip_fp16.h>");
    let _ = writeln!(out, "#include <hip/hip_bfloat16.h>");
    let _ = writeln!(out, "typedef hip_bfloat16 __hip_bfloat16;");
    let _ = writeln!(out, "#else");
    let _ = writeln!(out, "typedef uint16_t __half;");
    let _ = writeln!(out, "typedef uint16_t hip_bfloat16;");
    let _ = writeln!(out, "typedef uint16_t __hip_bfloat16;");
    let _ = writeln!(out, "#endif");
    let _ = writeln!(out);
    let _ = writeln!(out, "#ifndef KERNEL_PTR_ALIGNMENT_BYTES");
    let _ = writeln!(
        out,
        "#define KERNEL_PTR_ALIGNMENT_BYTES {}",
        KERNEL_PTR_ALIGNMENT_BYTES
    );
    let _ = writeln!(out, "#endif");
    let _ = writeln!(out);

    for (i, abi) in ordered.iter().enumerate() {
        if i > 0 {
            let _ = writeln!(out);
        }
        let _ = write!(out, "{}", emit_hip_struct(abi));
    }

    Ok(out)
}

/// Emits the complete standalone Rust module containing all provided ABI structs (Spec 4 §7).
pub fn emit_all_rust_module(structs: &[AbiStruct]) -> Result<String, crate::error::KgenError> {
    let ordered = sort_and_dedup_variants(structs)?;
    let mut out = String::new();
    let _ = writeln!(out, "// SPDX-License-Identifier: Apache-2.0");
    let _ = writeln!(
        out,
        "//! Auto-generated argument structs for kernel ABI (Spec 4 §7)."
    );
    let _ = writeln!(
        out,
        "//! Generated by r9v-kgen ABI generator. DO NOT HAND-EDIT."
    );
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "#![allow(dead_code, non_camel_case_types, unused_imports)]"
    );
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "pub const KERNEL_PTR_ALIGNMENT_BYTES: usize = {};",
        KERNEL_PTR_ALIGNMENT_BYTES
    );
    let _ = writeln!(out);

    for (i, abi) in ordered.iter().enumerate() {
        if i > 0 {
            let _ = writeln!(out);
        }
        let _ = write!(out, "{}", emit_rust_struct(abi));
    }

    Ok(out)
}
