"""Generate crates/r9v-format/src/iq_lut.rs from gguf-py 0.19.0 class data.

Reads the authoritative IQ codebooks (init_grid-decoded integer grids,
ksigns, kvalues) and emits them as Rust const arrays.

Usage (from the workspace root):
  python3 crates/r9v-format/tests/fixtures/r9v-format/gen_iq_lut.py
  python3 crates/r9v-format/tests/fixtures/r9v-format/gen_iq_lut.py --check
Default rewrites src/iq_lut.rs in place (then formats it with
`rustfmt --edition 2021`, matching the committed file). --check
regenerates in memory, formats, and fails loudly on any byte
difference; rerunning without --check must reproduce the committed
file byte-identically. Requires gguf-py 0.19.0 exactly (asserted
below): any gguf-py version change alters codebook bytes and must
fail here, never silently pass.

Decode through these tables was validated bit-exact via the A2.4
fixtures against local llama.cpp source commit
dd1ea524333b1e697489067d7a4c39c60d32beee (see the
iq_a24_reference.txt header); the table bytes themselves derive from
gguf-py class data only.
"""
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import numpy as np
from gguf import quants as Q

EXPECTED_GGUF_VERSION = "0.19.0"
SCRIPT_REL = "crates/r9v-format/tests/fixtures/r9v-format/gen_iq_lut.py"

import importlib.metadata as md

_gguf_version = md.version('gguf')
print(f"gguf-py {_gguf_version}", file=sys.stderr)
assert _gguf_version == EXPECTED_GGUF_VERSION, (
    f"gguf-py must be {EXPECTED_GGUF_VERSION}, found {_gguf_version}"
)

OUT_REL = Path("crates") / "r9v-format" / "src" / "iq_lut.rs"


def crate_file(name):
    return Path(__file__).resolve().parents[3] / "src" / name


def emit_u8(buf, name, arr, per_line=16):
    flat = np.asarray(arr, dtype=np.uint8).reshape(-1)
    buf.append(f'pub const {name}: [u8; {flat.size}] = [')
    for i in range(0, flat.size, per_line):
        buf.append('   ' + ', '.join(str(int(v)) for v in flat[i:i + per_line]) + ',')
    buf.append('];')


def emit_i8(buf, name, arr, per_line=16):
    flat = np.asarray(arr, dtype=np.int8).reshape(-1)
    buf.append(f'pub const {name}: [i8; {flat.size}] = [')
    for i in range(0, flat.size, per_line):
        buf.append('   ' + ', '.join(str(int(v)) for v in flat[i:i + per_line]) + ',')
    buf.append('];')


def build_body():
    buf = []
    buf.append('// SPDX-License-Identifier: Apache-2.0')
    buf.append('//! IQ codebook tables as auditable data (Spec 2 §3.3;')
    buf.append('//! phase-a-agent-breakdown.md card A2.4).')
    buf.append('//!')
    buf.append('//! GENERATED FILE — do not hand-edit. Generated by')
    buf.append(f'//! `{SCRIPT_REL}` from gguf-py 0.19.0 `quants.py` class data')
    buf.append('//! (`init_grid`-decoded integer grids, `ksigns`, `kvalues`).')
    buf.append('//! Regenerate with the same command and diff; any gguf-py version')
    buf.append('//! change alters codebook bytes and must fail the bit-exact tests,')
    buf.append('//! never silently pass. Decode through these tables was validated')
    buf.append('//! bit-exact via the A2.4 fixtures against local llama.cpp source')
    buf.append('//! commit dd1ea524333b1e697489067d7a4c39c60d32beee (see the')
    buf.append('//! `iq_a24_reference.txt` header for the 23,680/23,680-word receipt).')
    buf.append('//!')
    buf.append('//! Grids map packed codebook indices to signed-magnitude slots:')
    buf.append('//! the dequant formula multiplies the looked-up slot by the')
    buf.append('//! block scale and the sign (Spec 2 §3.3 IQ rows; SI-70).')
    buf.append('')
    buf.append('use crate::FormatError;')
    buf.append('')

    # IQ4 16-entry i8 codebook shared by IQ4_NL and IQ4_XS.
    kv = np.array(Q.IQ4_NL.kvalues, dtype=np.int8)
    assert kv.shape == (16,)
    buf.append('/// IQ4 codebook: 16 signed slots shared by `IQ4_NL` and `IQ4_XS`')
    buf.append('/// (gguf-py `IQ4_NL.kvalues`; `IQ4_XS` reuses `IQ4_NL.kvalues`).')
    emit_i8(buf, 'IQ4_KVALUES', kv)
    buf.append('')

    # 128-entry sign LUT shared by IQ2_XXS, IQ2_XS and IQ3_XXS.
    ks = np.frombuffer(Q.IQ2_XXS.ksigns, dtype=np.uint8)
    assert ks.shape == (128,)
    buf.append('/// Sign LUT: 128 bytes shared by `IQ2_XXS`, `IQ2_XS`, `IQ3_XXS`')
    buf.append('/// (gguf-py `IQ2_XXS.ksigns`; each 7-bit field selects one byte,')
    buf.append('/// each bit of that byte is one value sign, 0 -> +1, 1 -> -1).')
    emit_u8(buf, 'IQ_SIGN_LUT', ks)
    buf.append('')

    grids = [
        ('IQ2_XXS_GRID', Q.IQ2_XXS, 'u8', (256, 8), 'IQ2_XXS: 256 entries x 8 values'),
        ('IQ2_XS_GRID', Q.IQ2_XS, 'u8', (512, 8), 'IQ2_XS: 512 entries x 8 values'),
        ('IQ2_S_GRID', Q.IQ2_S, 'u8', (1024, 8), 'IQ2_S: 1024 entries x 8 values'),
        ('IQ3_XXS_GRID', Q.IQ3_XXS, 'u8', (256, 4), 'IQ3_XXS: 256 entries x 4 values'),
        ('IQ3_S_GRID', Q.IQ3_S, 'u8', (512, 4), 'IQ3_S: 512 entries x 4 values'),
        ('IQ1_GRID', Q.IQ1_S, 'i8', (2048, 8), 'IQ1_S/IQ1_M shared: 2048 entries x 8 values'),
    ]
    for cname, cls, kind, shape, doc in grids:
        cls.init_grid()
        g = np.asarray(cls.grid, dtype=np.float32).reshape(shape)
        assert g.shape == shape, (cname, g.shape)
        gi = np.round(g).astype(np.int64)
        assert np.array_equal(g, gi.astype(np.float32)), f'{cname} not integral'
        buf.append(f'/// {doc} (gguf-py `{cls.__name__}.grid`, `grid_map={cls.grid_map}`).')
        if kind == 'u8':
            assert gi.min() >= 0 and gi.max() <= 255, (cname, gi.min(), gi.max())
            emit_u8(buf, cname, gi.astype(np.uint8))
        else:
            assert gi.min() >= -128 and gi.max() <= 127, (cname, gi.min(), gi.max())
            emit_i8(buf, cname, gi.astype(np.int8))
        buf.append('')

    buf.append('/// Looks up one grid slot, bounds-checked against the table.')
    buf.append('///')
    buf.append('/// Every packed index is masked to its valid range at parse, so a')
    buf.append('/// well-formed repack never fails here; a hand-built tensor with a')
    buf.append('/// forged index is a length-style error, never a panic')
    buf.append('/// (CONVENTIONS.md §1.5).')
    buf.append('pub fn grid_slot(grid: &[u8], index: usize, what: &\'static str) -> Result<u8, FormatError> {')
    buf.append('    match grid.get(index) {')
    buf.append('        Some(slot) => Ok(*slot),')
    buf.append('        None => Err(FormatError::LengthMismatch {')
    buf.append('            what,')
    buf.append('            expected: (index + 1) as u64,')
    buf.append('            got: grid.len() as u64,')
    buf.append('        }),')
    buf.append('    }')
    buf.append('}')
    buf.append('')
    buf.append('/// Looks up one signed grid slot (`IQ1_*`), bounds-checked.')
    buf.append('pub fn grid_slot_signed(grid: &[i8], index: usize, what: &\'static str) -> Result<i8, FormatError> {')
    buf.append('    match grid.get(index) {')
    buf.append('        Some(slot) => Ok(*slot),')
    buf.append('        None => Err(FormatError::LengthMismatch {')
    buf.append('            what,')
    buf.append('            expected: (index + 1) as u64,')
    buf.append('            got: grid.len() as u64,')
    buf.append('        }),')
    buf.append('    }')
    buf.append('}')
    return '\n'.join(buf) + '\n'


def rustfmt_text(text):
    exe = shutil.which("rustfmt")
    assert exe, "rustfmt not found on PATH; install the Rust toolchain"
    with tempfile.NamedTemporaryFile("w", suffix=".rs", delete=False) as f:
        f.write(text)
        tmp = f.name
    try:
        subprocess.run([exe, "--edition", "2021", tmp], check=True)
        return Path(tmp).read_text()
    finally:
        Path(tmp).unlink(missing_ok=True)


def main():
    out = crate_file("iq_lut.rs")
    body = build_body()
    formatted = rustfmt_text(body)
    if "--check" in sys.argv[1:]:
        committed = out.read_text()
        if committed != formatted:
            print(f"--check FAILED: regen differs from committed {OUT_REL}")
            sys.exit(1)
        print(f"--check OK: regen reproduces {OUT_REL.name} byte-identically")
    else:
        out.write_text(formatted)
        print("wrote", out)


main()
